### ISSUE TITLE
能不能支持复用现有的webui

### ISSUE THREAD

**Issue by yh4922** [liriliri/vivy-docs#1]

**Comment by surunzi** [comment]
你是指使用本地已经装好的 webui 来提供 api？

**Comment by yh4922** [comment]
是的

**Comment by surunzi** [comment]
后续会支持

**Comment by surunzi** [comment]
0.11.0 版本已支持自定义 web UI，下边是使用秋叶 directml 整合包的配置示例。
 
<img width="368" alt="1713834338940" src="https://github.com/liriliri/vivy-docs/assets/3487535/754d1e07-2af6-43b7-a40a-d3f24d4e9646">
