### ISSUE TITLE
Image viewer

### ISSUE THREAD

**Issue by cbresciano** [liriliri/vivy-docs#5]
I have some pictures in the F:\images directory, that can´t be loaded by the image viewer located at the bottom of the window. I know it because I can view them with the windows file manager and also clicking the folder button, beside the "save all" button
The Image Viewer doesn´t load all the images at start. I had to use "<-" for the other images, to see some of them. Some of the work seems not saved with the other images with "sava all" button. I have to test it a bit more but I´m sure I clicked the button to save them.

**Comment by surunzi** [comment]
I'm sorry if I wasn't clear. All generated images will not be automatically saved to the disk, nor loaded from the disk. You can save all the current images along with the generation parameters into a file with the ".vivy" extension, and then load this file when you open it next time. Finally, when you have the desired image, you can export it as a separate image file using the save button.
